[package]
name = "formatter"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
dprint-core = { version = "0.59.0", features = ["formatting", "wasm"] }
dprint-plugin-typescript = { version = "0.78.0" }
